### ISSUE TITLE
There is 404 error in the simulator repository

### ISSUE THREAD

**Issue by huanpass** [SwarmArch/T4#1]
Hi, 

It looks like the source folder of simulator deleted? Will it be possible to recover the folder back? 

Many thanks, 
Edward

**Comment by gmfff** [comment]
Did you find the source?

**Comment by gmfff** [comment]
> Hi,
> 
> It looks like the source folder of simulator deleted? Will it be possible to recover the folder back?
> 
> Many thanks,
> Edward
Did you find the source?

**Comment by VictorYing** [comment]
Hi, if you pull commit d443b669cf3557c276fb5a73a2b6a2af78066196 in this repository, then you should be all set to find the simulator source repo with `git submodule update --init --recursive`. If you don't need the T4 compiler and just want to experiment with Swarm itself, you can also get the simulator from https://github.com/SwarmArch/sim

Let me know if you still have any difficulty getting the code.
